/* Generated By:JavaCC: Do not edit this line. Linguagem20192TokenManager.java */

/** Token Manager. */
public class Linguagem20192TokenManager implements Linguagem20192Constants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 9:
         jjmatchedKind = 2;
         return jjMoveNfa_0(3, 0);
      case 10:
         jjmatchedKind = 3;
         return jjMoveNfa_0(3, 0);
      case 12:
         jjmatchedKind = 5;
         return jjMoveNfa_0(3, 0);
      case 13:
         jjmatchedKind = 4;
         return jjMoveNfa_0(3, 0);
      case 32:
         jjmatchedKind = 1;
         return jjMoveNfa_0(3, 0);
      case 33:
         jjmatchedKind = 36;
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 37:
         jjmatchedKind = 30;
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 38:
         jjmatchedKind = 34;
         return jjMoveNfa_0(3, 0);
      case 40:
         jjmatchedKind = 24;
         return jjMoveNfa_0(3, 0);
      case 41:
         jjmatchedKind = 25;
         return jjMoveNfa_0(3, 0);
      case 42:
         jjmatchedKind = 32;
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 43:
         jjmatchedKind = 27;
         return jjMoveNfa_0(3, 0);
      case 44:
         jjmatchedKind = 21;
         return jjMoveNfa_0(3, 0);
      case 45:
         jjmatchedKind = 28;
         return jjMoveNfa_0(3, 0);
      case 46:
         jjmatchedKind = 20;
         return jjMoveNfa_0(3, 0);
      case 47:
         jjmatchedKind = 33;
         return jjMoveStringLiteralDfa1_0(0xc0L);
      case 60:
         return jjMoveStringLiteralDfa1_0(0xa0000L);
      case 61:
         jjmatchedKind = 26;
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 62:
         return jjMoveStringLiteralDfa1_0(0x4000000050000L);
      case 65:
         return jjMoveStringLiteralDfa1_0(0xa400000000000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x10000000000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x240800000000000L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x2000000000L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x400000000000000L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x20120000000000L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x10008000000000L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x80080000000000L);
      case 85:
         return jjMoveStringLiteralDfa1_0(0x100000000000000L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L);
      case 91:
         jjmatchedKind = 22;
         return jjMoveNfa_0(3, 0);
      case 93:
         jjmatchedKind = 23;
         return jjMoveNfa_0(3, 0);
      case 97:
         return jjMoveStringLiteralDfa1_0(0xa400000000000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x10000000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x240800000000000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x2000000000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x400000000000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x20120000000000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x10008000000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x80080000000000L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x100000000000000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L);
      case 124:
         jjmatchedKind = 35;
         return jjMoveNfa_0(3, 0);
      default :
         return jjMoveNfa_0(3, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(3, 0);
   }
   switch(curChar)
   {
      case 37:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 1;
         }
         break;
      case 42:
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 7;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 1;
         }
         break;
      case 47:
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 6;
            jjmatchedPos = 1;
         }
         break;
      case 60:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x80000L);
      case 61:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 1;
         }
         break;
      case 62:
         if ((active0 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x50000L);
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x201000000000000L);
      case 67:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x204000000000L);
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x50080000000000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x100002000000000L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x810000000000L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x80020000000000L);
      case 83:
         if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000000L);
      case 84:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x420100000000000L);
      case 88:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x201000000000000L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x204000000000L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x50080000000000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x100002000000000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x810000000000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x80020000000000L);
      case 115:
         if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x420100000000000L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(3, 1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(3, 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(3, 1);
   }
   switch(curChar)
   {
      case 61:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 2;
         }
         break;
      case 62:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 2;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x40040000000000L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x10030000000000L);
      case 81:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000L);
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0x201108000000000L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000L);
      case 84:
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x100002000000000L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x40040000000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x10030000000000L);
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x201108000000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000L);
      case 116:
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x100002000000000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(3, 2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(3, 2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(3, 2);
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0x40040000000000L);
      case 69:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000L);
      case 71:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x3008000000000L);
      case 76:
         if ((active0 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x210000000000L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000000L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x300000000000000L);
      case 83:
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L);
      case 85:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000L);
      case 87:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 3;
         }
         break;
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x40040000000000L);
      case 101:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000L);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x3008000000000L);
      case 108:
         if ((active0 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x210000000000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x300000000000000L);
      case 115:
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000L);
      case 119:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 3;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(3, 3);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(3, 3);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(3, 3);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x1200000000000L);
      case 69:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      case 71:
         return jjMoveStringLiteralDfa5_0(active0, 0x2002000000000L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L);
      case 75:
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 4;
         }
         break;
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x100040000000000L);
      case 89:
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 4;
         }
         break;
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x1200000000000L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x2002000000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L);
      case 107:
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 4;
         }
         break;
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x100040000000000L);
      case 121:
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 4;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(3, 4);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(3, 4);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(3, 4);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x830000000000L);
      case 66:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000000L);
      case 69:
         if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000L);
      case 71:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 5;
         }
         break;
      case 78:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 5;
         }
         break;
      case 82:
         return jjMoveStringLiteralDfa6_0(active0, 0x8200000000000L);
      case 83:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L);
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x830000000000L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000000L);
      case 101:
         if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000L);
      case 103:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 5;
         }
         break;
      case 110:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 5;
         }
         break;
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x8200000000000L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(3, 5);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(3, 5);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(3, 5);
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 6;
         }
         break;
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000L);
      case 77:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 6;
         }
         break;
      case 78:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000L);
      case 82:
         if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 6;
         }
         break;
      case 101:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 6;
         }
         break;
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000L);
      case 109:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 6;
         }
         break;
      case 110:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000L);
      case 114:
         if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 6;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(3, 6);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(3, 6);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(3, 6);
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 7;
         }
         break;
      case 84:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 7;
         }
         break;
      case 101:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 7;
         }
         break;
      case 116:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 7;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(3, 7);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int strKind = jjmatchedKind;
   int strPos = jjmatchedPos;
   int seenUpto;
   input_stream.backup(seenUpto = curPos + 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { throw new Error("Internal Error"); }
   curPos = 0;
   int startsAt = 0;
   jjnewStateCnt = 33;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 60)
                        kind = 60;
                     jjCheckNAddStates(0, 2);
                  }
                  else if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 9:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAdd(11);
                  break;
               case 11:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 12:
                  if (curChar == 34 && kind > 62)
                     kind = 62;
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(3, 6);
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(19);
                  break;
               case 21:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAddStates(0, 2);
                  break;
               case 22:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L && kind > 61)
                     kind = 61;
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(7, 10);
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(22);
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(27, 22);
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(11, 13);
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAddTwoStates(31, 32);
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L && kind > 60)
                     kind = 60;
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(31);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 63)
                        kind = 63;
                     jjCheckNAddStates(14, 16);
                  }
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  else if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 0:
                  if ((0x2000000020L & l) != 0L && kind > 59)
                     kind = 59;
                  break;
               case 1:
               case 4:
                  if ((0x20000000200000L & l) != 0L)
                     jjCheckNAdd(0);
                  break;
               case 2:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 5:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 10:
                  jjCheckNAdd(11);
                  break;
               case 11:
                  jjCheckNAddTwoStates(11, 12);
                  break;
               case 13:
                  if ((0x7fffffeL & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddStates(14, 16);
                  break;
               case 14:
                  if (curChar == 95 && kind > 63)
                     kind = 63;
                  break;
               case 15:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddTwoStates(15, 16);
                  break;
               case 18:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddStates(17, 19);
                  break;
               case 19:
                  if (curChar != 95)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddTwoStates(15, 16);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 10:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAdd(11);
                  break;
               case 11:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 33 - (jjnewStateCnt = startsAt)))
         break;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { break; }
   }
   if (jjmatchedPos > strPos)
      return curPos;

   int toRet = Math.max(curPos, seenUpto);

   if (curPos < toRet)
      for (i = toRet - Math.min(curPos, seenUpto); i-- > 0; )
         try { curChar = input_stream.readChar(); }
         catch(java.io.IOException e) { throw new Error("Internal Error : Please send a bug report."); }

   if (jjmatchedPos < strPos)
   {
      jjmatchedKind = strKind;
      jjmatchedPos = strPos;
   }
   else if (jjmatchedPos == strPos && jjmatchedKind > strKind)
      jjmatchedKind = strKind;

   return toRet;
}
private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 8);
      case 13:
         jjmatchedKind = 9;
         return jjMoveStringLiteralDfa1_1(0x400L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_1(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 10:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(1, 10);
         break;
      default :
         return 2;
   }
   return 2;
}
private int jjMoveStringLiteralDfa0_2()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_2(0x1000L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_2(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(1, 12);
         break;
      default :
         return 2;
   }
   return 2;
}
static final int[] jjnextStates = {
   22, 26, 30, 17, 15, 20, 19, 27, 22, 28, 29, 27, 22, 28, 14, 15, 
   16, 19, 15, 16, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\75\75", "\41\75", "\76\76\76", "\74\74", "\76\76\75", "\74\74\75", "\56", 
"\54", "\133", "\135", "\50", "\51", "\75", "\53", "\55", "\45\45", "\45", "\52\52", 
"\52", "\57", "\46", "\174", "\41", null, null, null, null, null, null, null, null, 
null, null, null, null, null, "\76\76", null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "singlelinecomment",
   "multilinecomment",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, 1, 2, 0, 0, 0, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffc001L, 0x0L, 
};
static final long[] jjtoSkip = {
   0x3ffeL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[33];
private final int[] jjstateSet = new int[66];
protected char curChar;
/** Constructor. */
public Linguagem20192TokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public Linguagem20192TokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 33; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 3 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   switch(curLexState)
   {
     case 0:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       if (jjmatchedPos == 0 && jjmatchedKind > 11)
       {
          jjmatchedKind = 11;
       }
       break;
     case 2:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_2();
       if (jjmatchedPos == 0 && jjmatchedKind > 13)
       {
          jjmatchedKind = 13;
       }
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
