/* Generated By:JavaCC: Do not edit this line. Linguagem20191Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Linguagem20191Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOT = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int OPEN_CURLY_BRACKET = 13;
  /** RegularExpression Id. */
  int CLOSED_CURLY_BRACKET = 14;
  /** RegularExpression Id. */
  int OPEN_PARENTHESE = 15;
  /** RegularExpression Id. */
  int CLOSED_PARENTHESE = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int DIVISION_REST = 19;
  /** RegularExpression Id. */
  int EXACT_DIVISION = 20;
  /** RegularExpression Id. */
  int POW = 21;
  /** RegularExpression Id. */
  int MULTIPLY = 22;
  /** RegularExpression Id. */
  int DIVIDE = 23;
  /** RegularExpression Id. */
  int EQUAL = 24;
  /** RegularExpression Id. */
  int DIFFERENT = 25;
  /** RegularExpression Id. */
  int MORE_EQUAL = 26;
  /** RegularExpression Id. */
  int LESS_EQUAL = 27;
  /** RegularExpression Id. */
  int MORE_ = 28;
  /** RegularExpression Id. */
  int LESS = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int NOT = 32;
  /** RegularExpression Id. */
  int NATURAL = 33;
  /** RegularExpression Id. */
  int REAL = 34;
  /** RegularExpression Id. */
  int CHAR = 35;
  /** RegularExpression Id. */
  int BOOLEAN = 36;
  /** RegularExpression Id. */
  int PROGRAM = 37;
  /** RegularExpression Id. */
  int DEFINE = 38;
  /** RegularExpression Id. */
  int _NOT = 39;
  /** RegularExpression Id. */
  int VARIABLE = 40;
  /** RegularExpression Id. */
  int IS = 41;
  /** RegularExpression Id. */
  int EXECUTE = 42;
  /** RegularExpression Id. */
  int SET = 43;
  /** RegularExpression Id. */
  int TO = 44;
  /** RegularExpression Id. */
  int GET = 45;
  /** RegularExpression Id. */
  int PUT = 46;
  /** RegularExpression Id. */
  int VERIFY = 47;
  /** RegularExpression Id. */
  int _TRUE = 48;
  /** RegularExpression Id. */
  int _FALSE = 49;
  /** RegularExpression Id. */
  int LOOP = 50;
  /** RegularExpression Id. */
  int WHILE = 51;
  /** RegularExpression Id. */
  int INTEGER_CONSTANT = 52;
  /** RegularExpression Id. */
  int REAL_CONSTANT = 53;
  /** RegularExpression Id. */
  int DIGIT = 54;
  /** RegularExpression Id. */
  int LOGIC_CONSTANT = 55;
  /** RegularExpression Id. */
  int IDENTIFIER = 56;
  /** RegularExpression Id. */
  int LITERAL_CONSTANT = 57;
  /** RegularExpression Id. */
  int LETTER = 58;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\":-\"",
    "\"\\n\"",
    "<token of kind 10>",
    "\".\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"%%\"",
    "\"%\"",
    "\"**\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"natural\"",
    "\"real\"",
    "\"char\"",
    "\"boolean\"",
    "\"program\"",
    "\"define\"",
    "\"not\"",
    "\"variable\"",
    "\"is\"",
    "\"execute\"",
    "\"set\"",
    "\"to\"",
    "\"get\"",
    "\"put\"",
    "\"verify\"",
    "\"true\"",
    "\"false\"",
    "\"loop\"",
    "\"while\"",
    "<INTEGER_CONSTANT>",
    "<REAL_CONSTANT>",
    "<DIGIT>",
    "<LOGIC_CONSTANT>",
    "<IDENTIFIER>",
    "<LITERAL_CONSTANT>",
    "<LETTER>",
  };

}
