/* Generated By:JavaCC: Do not edit this line. LinguagemTreeConstants.java Version 5.0 */
public interface LinguagemTreeConstants
{
  public int JJTSTART = 0;


  public String[] jjtNodeName = {
    "Start",
  };
}
/* JavaCC - OriginalChecksum=89118e5d5a11ac9a221f7f5eb19efbd9 (do not edit this line) */
