/* Generated By:JJTree&JavaCC: Do not edit this line. LinguagemConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LinguagemConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOT = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int OPEN_CURLY_BRACKET = 9;
  /** RegularExpression Id. */
  int CLOSED_CURLY_BRACKET = 10;
  /** RegularExpression Id. */
  int OPEN_PARENTHESE = 11;
  /** RegularExpression Id. */
  int CLOSED_PARENTHESE = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int DIVISION_REST = 15;
  /** RegularExpression Id. */
  int EXACT_DIVISION = 16;
  /** RegularExpression Id. */
  int POW = 17;
  /** RegularExpression Id. */
  int MULTIPLY = 18;
  /** RegularExpression Id. */
  int DIVIDE = 19;
  /** RegularExpression Id. */
  int EQUAL = 20;
  /** RegularExpression Id. */
  int DIFFERENT = 21;
  /** RegularExpression Id. */
  int MORE_EQUAL = 22;
  /** RegularExpression Id. */
  int LESS_EQUAL = 23;
  /** RegularExpression Id. */
  int MORE_ = 24;
  /** RegularExpression Id. */
  int LESS = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int OR = 27;
  /** RegularExpression Id. */
  int NOT = 28;
  /** RegularExpression Id. */
  int NATURAL = 29;
  /** RegularExpression Id. */
  int REAL = 30;
  /** RegularExpression Id. */
  int CHAR = 31;
  /** RegularExpression Id. */
  int BOOLEAN = 32;
  /** RegularExpression Id. */
  int PROGRAM = 33;
  /** RegularExpression Id. */
  int DEFINE = 34;
  /** RegularExpression Id. */
  int _NOT = 35;
  /** RegularExpression Id. */
  int VARIABLE = 36;
  /** RegularExpression Id. */
  int IS = 37;
  /** RegularExpression Id. */
  int EXECUTE = 38;
  /** RegularExpression Id. */
  int SET = 39;
  /** RegularExpression Id. */
  int TO = 40;
  /** RegularExpression Id. */
  int GET = 41;
  /** RegularExpression Id. */
  int PUT = 42;
  /** RegularExpression Id. */
  int VERIFY = 43;
  /** RegularExpression Id. */
  int _TRUE = 44;
  /** RegularExpression Id. */
  int _FALSE = 45;
  /** RegularExpression Id. */
  int LOOP = 46;
  /** RegularExpression Id. */
  int WHILE = 47;
  /** RegularExpression Id. */
  int IDENTIFIER = 48;
  /** RegularExpression Id. */
  int LOGIC_CONSTANT = 49;
  /** RegularExpression Id. */
  int INTEGER_CONSTANT = 50;
  /** RegularExpression Id. */
  int REAL_CONSTANT = 51;
  /** RegularExpression Id. */
  int DIGIT = 52;
  /** RegularExpression Id. */
  int LITERAL_CONSTANT = 53;
  /** RegularExpression Id. */
  int LETTER = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\".\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"%%\"",
    "\"%\"",
    "\"**\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"natural\"",
    "\"real\"",
    "\"char\"",
    "\"boolean\"",
    "\"program\"",
    "\"define\"",
    "\"not\"",
    "\"variable\"",
    "\"is\"",
    "\"execute\"",
    "\"set\"",
    "\"to\"",
    "\"get\"",
    "\"put\"",
    "\"verify\"",
    "\"true\"",
    "\"false\"",
    "\"loop\"",
    "\"while\"",
    "<IDENTIFIER>",
    "<LOGIC_CONSTANT>",
    "<INTEGER_CONSTANT>",
    "<REAL_CONSTANT>",
    "<DIGIT>",
    "<LITERAL_CONSTANT>",
    "<LETTER>",
  };

}
